### ISSUE TITLE
Swimlane 1871 gewollt?

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/lernOS-Prozessmodellierung#106]
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#von-pools-und-lanes-lu-pools

Swimlane 1871 gewollt?

**Comment by rednaxelaesor** [comment]
Hallo @bnaflvct ,
das verstehe ich nicht.

Pool ist LV 1871. Lanes sind Vertrieb & Logistik

**Comment by bnaflvct** [comment]
Hi @rednaxelaesor ,
genau "Pool ist LV 1871", also ein konkretes Unternehmen.
Soweit ich das richtig Überblicke ist es die einzige Stelle, wo eine konkrete Firma genannt wird und ist im Kontext nicht selbsterklärend.
Jemand der die LV 1871 nicht kennt versteht dieses Bild schwerer.

Ich dachte daran vielleicht einfach "Unternehmen" oder "Firma" zu verwenden.

**Comment by rednaxelaesor** [comment]
Auch ein gutes Argument. Um generich zu bleiben, sollte ich das auch anändern.
