### ISSUE TITLE
Eventuell "Pizza bestellen" sendenter Prozess?

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/lernOS-Prozessmodellierung#108]
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#blanko-zwischenereignis
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#nachrichten-zwischenereignis

eventuell "Pizza bestellen" sendenter Prozess?

**Comment by rednaxelaesor** [comment]
Hallo @bnaflvct , meinst Du hier: "Aufgabentyp" senden?

**Comment by bnaflvct** [comment]
Hi @rednaxelaesor,

man könnte dem sendenden Task noch eine Markierung hinzufügen aus https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#exkurs---markierungen-aufgabentypen--daten-lu-markierungen

**Comment by rednaxelaesor** [comment]
Die Aufgabentypern wurden wurden vorher eingeführt. Es macht Sinn sie gleich in der nächsten Übung zu verwenden.
