### ISSUE TITLE
Dein erstes komplexes DRD Übungen erstellen

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/lernOS-Prozessmodellierung#18]

**Comment by rednaxelaesor** [comment]
Wenn uns nichts besseres einfällt, können wir die Errechnung der PL-Zulage als KATA nutzen

**Comment by rednaxelaesor** [comment]
Eine weitere Idee ist die Tee Zeremonie weiter zu verfolgen,

TeeART: Schwarz, Grün, Kräuter, Roibusch
Tee-Geschmack (LAAAANGE-Liste)
TeeContainment (Beutel, Kapsel, lose)
Ziehzeit: 3,5,8 und 12 Minuten
Veredelung: Milch (laktosefrei, Soya, ...), Zucker (Weiss, Braun, Kandis), Honig (fest, flüssig), Süsstoff (fest, flüssig), Stevia

**Comment by rednaxelaesor** [comment]
Termin: 31.01.2020

**Comment by bnaflvct** [comment]
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/%2318-Dein-erstes-komplexes-DRD-%C3%9Cbungen-erstellen/de/lernOS-Prozessmodellierung-de.md#dein-erstes-komplexes-drd-kata-10-kata10
