### ISSUE TITLE
Interne Link-Referenzen entfernen oder korrigieren

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/lernOS-Prozessmodellierung#47]

**Comment by rednaxelaesor** [comment]
Derzeit funktionieren die internen Referenzen nur im MD. Beim Export funktionieren die Links nicht mehr

**Comment by yogi11** [comment]
@rednaxelaesor Habe mal einen Branch mit einem Beispiel für Kata 09 erstellt. Magst mal testen, ob's bei Dir auch mit den internen Links funktioniert, dann würde ich die restlichen Links überarbeiten.

**Comment by rednaxelaesor** [comment]
Hallo @yogi11 ,
was genau hast Du denn gemacht? Folgendes habe ich gesehen:

- Überschrift der Kata um  {#kata09} ergänzt
- Rücksprungadresse aus dem Lerninhalt mit #kata09 aufgerufen

Ergebnis: In Typora funktioniert der Rücksprung nicht (Wird zwar als Link erkannt, aber passiert nix beim klicken)
Im PDF wird der Rücksprung noch nicht einmal als Link erkannt. (Mauszeiger ändert sich nicht)

Weiterhin: Es ist eine neue Datei build.sh im Verzeichnis erzeugt worden.

LG Alex.

**Comment by rednaxelaesor** [comment]
Hallo @yogi11 ,
was genau hast Du denn gemacht? Folgendes habe ich gesehen:

Überschrift der Kata um {#kata09} ergänzt
Rücksprungadresse aus dem Lerninhalt mit #kata09 aufgerufen
Ergebnis: In Typora funktioniert der Rücksprung nicht (Wird zwar als Link erkannt, aber passiert nix beim klicken - was nicht so schlimm ist)
PDF: Rücksprung funktioniert :-) - Andre Formate teste ich noch.
[lernOS-Prozessmodellierung-de.pdf](https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/files/4081198/lernOS-Prozessmodellierung-de.pdf)


Weiterhin: Es ist eine neue Datei build.sh im Verzeichnis erzeugt worden.

LG Alex.

**Comment by yogi11** [comment]
@rednaxelaesor Bei mir kann ich im PDF mit dem Link auf Seite 44 "Zurück zur KATA" auf die Seite 10, Kapitel 4.9 springen - so, wie ich es mir erhofft habe. Funktioniert sowohl im Adobe Reader als auch in der Mac-internen PDF-Vorschau.
Die neue Datei brauche ich zum Bauen unter MacOS.

**Comment by yogi11** [comment]
@rednaxelaesor In dem PDF, welches in Deiner Antwort ist, funktioniert der Link auch ;-)

**Comment by yogi11** [comment]
@rednaxelaesor Bin zu blöd zum Lesen :-( Du hast ja schon geschrieben, dass es im PDF geht
Ich korrigiere dann mal morgen alle internen Links und stelle das das MD im Branch zum Merge bereit

**Comment by rednaxelaesor** [comment]
@yogi11 Ist gemerged. Der Sprung zu den Lernunterlegen landet immer am Anfang des Dokumentes.

**Comment by yogi11** [comment]
> @yogi11 Ist gemerged. Der Sprung zu den Lernunterlegen landet immer am Anfang des Dokumentes.

@rednaxelaesor Kannst Du mir bitte ein Beispiel nennen. Habe ich womöglich einige Links übersehen.

**Comment by rednaxelaesor** [comment]
@yogi11 : In jeder Kata (außer 1 und 11) ist eine Sprungadresse zum Lerninhalt. 
![image](https://user-images.githubusercontent.com/25124078/72688349-73640a00-3b06-11ea-9283-0b92d69ad015.png)

**Comment by rednaxelaesor** [comment]
Nach dem Merge keine FM bei der Erzeugung von Mobi. Damit kann Prüfung nach Ralfs Änderungen ob die u.s. Links immer noch diese Fehler erzeugen #71 geschlossen werden..

**Comment by rednaxelaesor** [comment]
Die Links funktionieren jetzt in allen Formaten.
Juhu !!!
