### ISSUE TITLE
Aktuelles Feedback zum Lernpfad geben - Hans

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/lernOS-Prozessmodellierung#57]
Hierzu sollte der Lernpfad einmal ~~komplett~~ gelesen werden. 
Diese Story richtet sich auf  die Kapitel:

- [ ] - Lernpfad Prozessmodellierung
- [ ] - Lernunterlagen

Hier soll sich insbesondere auf:
- TYPO
- Bilder
- Methodik
konzentriert werden.

Typo kann gerne sofort angepasst werden.

Bei Bilder und Methodik reicht Screenshot oder jede Dir passende Form an @rednaxelaesor

**Comment by rednaxelaesor** [comment]
Hallo @HFacher,
kommt zu diesem Thema noch etwas von Dir - Oder passt soweit dann alles?

LG Alex

**Comment by HFacher** [comment]
Hallo @rednaxelaesor ,

da kommt noch was von mir. Ich schau, dass ich es die Woche noch liefern kann.
