### ISSUE TITLE
Aktuelles Feedback zum Lernpfad geben & einarbeiten - Ralf

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/lernOS-Prozessmodellierung#58]
Hierzu sollte der Lernpfad einmal ~~komplett~~ gelesen werden. 
Diese Story richtet sich auf  die Kapitel:

- [x] - Lernpfad Prozessmodellierung
- [x] - Lernunterlagen

Hier soll sich insbesondere auf:
- TYPO
- Bilder
- Methodik
konzentriert werden.

Typo kann gerne sofort angepasst werden.

Bei Bilder und Methodik reicht Screenshot oder jede Dir passende Form an @rednaxelaesor

**Comment by yogi11** [comment]
@rednaxelaesor 

Hier noch ein Anmerkungen, welche ich nicht im Dokument auftauchen, da sie eher zu diskutieren, als direkt zu überarbeiten sind
- Kata 3 eher nur 60 Minuten, dafür Kata 5 90 Minuten (brauchte schon 10 Minuten, um die Aufgabe zu lesen und zu verstehen
- Kata 6 - welche Events sind hier schon bekannt (Start & Ende?) - explizit kommen sie bisher nicht vor
- Kata 8 - Als Ergebnis soll genau eine Entscheidungstabelle rauskommen. Die Lernunterlagen sind allerdings sehr umfangreich und beinhalten auch weit mehr als die Notation von Entscheidungstabellen. Da können die 60 Minuten auch en werden. Daher sollten wir Kata/Lernunterlagen nochmal entzerren. Vielleicht in der nächsten Version eine zusätzliche/alternative Kata einführen?
- Kata 9 - Soll da noch eine Bonusaufgabe rein, wie das Ergebnis mit unterschiedlichen Hit-Policies aussieht? Sonst kommen eigentlich nur Datentypen vor, oder?

**Comment by yogi11** [comment]
@rednaxelaesor 

Beim Thema DMN, Datentypen und Operatoren würde ich gern demnächst etwas didaktisch sortieren. Hier springen wir zu sehr zwischen den Typen, Mengenoperatoren etc. hin und her. Hier könnte ein Hinweis auf FEEL als Zwischenkapitel helfen, mehr Struktur reinzubringen.

Zusätzlich wird auf Seite 42 der Wert "-" (any) im Rahmen der Hit-Policies eingeführt. Das passt für mich eher zu den Datentypen bzw. deren Ausprägungen im Kapitel davor und führt an dieser Stelle ggf. zu Verwirrung im Bezug auf die gleichnamige Hit-Policy

**Comment by rednaxelaesor** [comment]
Danke @yogi11 
der Branch ist gemerged. Ich übernehme diese Story und schaue mal was ich davon wie verwurste.

Vielen Dank!

**Comment by rednaxelaesor** [comment]
Hallo @yogi11 

> Kata 3 eher nur 60 Minuten, dafür Kata 5 90 Minuten (brauchte schon 10 Minuten, um die Aufgabe zu lesen und zu verstehen

- [ ] Eingebaut

> Kata 6 - welche Events sind hier schon bekannt (Start & Ende?) - explizit kommen sie bisher nicht vor
-> Bereits in Kata 01 & 02 kommst Du an Start und Ende nicht vorbei

**Comment by rednaxelaesor** [comment]
- [ ] Kata 8 - Als Ergebnis soll genau eine Entscheidungstabelle rauskommen. Die Lernunterlagen sind allerdings sehr umfangreich und beinhalten auch weit mehr als die Notation von Entscheidungstabellen. Da können die 60 Minuten auch en werden. Daher sollten wir Kata/Lernunterlagen nochmal entzerren. Vielleicht in der nächsten Version eine zusätzliche/alternative Kata einführen?

- [ ] Kata 9 - Soll da noch eine Bonusaufgabe rein, wie das Ergebnis mit unterschiedlichen Hit-Policies aussieht? Sonst kommen eigentlich nur Datentypen vor, oder?
