### ISSUE TITLE
Aktuelles Feedback zum Lernpfad geben - Benedikt

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/lernOS-Prozessmodellierung#59]
Hierzu sollte der Lernpfad einmal ~~komplett~~ gelesen werden. 
Diese Story richtet sich auf  die Kapitel:

- [x] - Lernpfad Prozessmodellierung
- [x] - Lernunterlagen

Hier soll sich insbesondere auf:
- TYPO
- Bilder
- Methodik
konzentriert werden.

Typo kann gerne sofort angepasst werden.

Bei Bilder und Methodik reicht Screenshot oder jede Dir passende Form an @rednaxelaesor

**Comment by bnaflvct** [comment]
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#was-ist-bpmn

BPMN is auch von OMG (siehe DMN)
ISO-Norm: 19510:2013​ -> https://www.omg.org/spec/BPMN/ISO/19510/PDF

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#triff-deine-ersten-entscheidungen-kata-03-kata03

`**beliebigen Prozess( )**`

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#exklusive-gateway-xor-split-und-join

Typo im Bild https://raw.githubusercontent.com/rednaxelaesor/lernOS-Prozessmodellierung/master/de/images/Exklusive-Gateways-(XOR)-Split-%26-Join.png
Exklusives Ga(r)[t]eway

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#von-pools-und-lanes-lu-pools

Swimlane 1871 gewollt?

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#von-pools-und-lanes-lu-pools

Von der Personenbenennung ist jedoch abzuraten, da sich Personen ständig ändern können. Nutze in dem Fall besser die prozessbezogenen Rollen.

Sabine, Ralf und Alex wollen etwas kochen. Jeder bekommt Aufgaben zugewiesen.

-> Text zu Bild - Tu das nicht, aber wir tun es jetzt?

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#blanko-zwischenereignis
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#nachrichten-zwischenereignis

eventuell "Pizza bestellen" sendenter Prozess?

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#exkurs---markierungen-aufgabentypen--daten-lu-markierungen

Im der Aufgabe https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#exkurs---markierungen-aufgabentypen--daten-lu-markierungen
wird von Attributen gesprochen, in den Lernunterlagen nicht?

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#datentypen-und-hit-policy-kata-09-kata09

"Hit-Policies bestimmen, wie die Entscheidungstabelle mit Eingaben umgeht, die [genau eine, ]mehrere oder gar keine Regeln erfüllen."

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#datentypen-und-hit-policy-kata-09-kata09

Welche Mitglieder hat ein Autoverleih?

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#dein-meisterst%C3%BCck-kata-11-kata11

"Diese Variante dauert aber erheblich länger." klingt irgendwie zu negativ - könnte man vielleicht positiver, auffordernder formulieren, wie "Diese Variante dauert natürlich länger, bitte beachte das bei Deiner Zeitplanung"

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#datentypen-f%C3%BCr-input-data-elemente

Hierarchie: Abteilungsleiter, Teamleiter, Mitarbeiter?

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#aufz%C3%A4hlung
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#hierarchie

? Kenn ich so nicht -> Enum, Liste?

---
https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-de.md#any-hit-policy-a

https://github.com/rednaxelaesor/lernOS-Prozessmodellierung/raw/master/de/images/ANY-hit-policy.png
Bild Link broken
