### ISSUE TITLE
Releasebildung in GIT verstehen

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/lernOS-Prozessmodellierung#67]

**Comment by yogi11** [comment]
Ist recht simpel nach dieser Beschreibung hier: https://help.github.com/en/github/administering-a-repository/creating-releases
Nach meinem Verständnis im halbmanuellen Modus:

- Tag auf die Version im Master-Branch
- Lokal bauen
- Artefakte ins Release laden

**Comment by rednaxelaesor** [comment]
@yogi11 Ich habe das mal im Test gemacht. Die Artefakte werden automatisch in zwei komprimierte Datein verpackt.

![image](https://user-images.githubusercontent.com/25124078/72756007-467a2a80-3bcc-11ea-8555-d85818292a57.png)

**Comment by rednaxelaesor** [comment]
@yogi11 Habe ein Prebuild erzeugt. Sieht gut aus. Schau mal rein.

**Comment by yogi11** [comment]
Das schaut schon sehr gut aus - nur die Generate sind doppelt vorhanden: im ZIP-File und als Einzeldateien. Das lässt sich aber vermutlich noch optimieren.
