### ISSUE TITLE
Generate in Unterverzeichnis erzeugen

### ISSUE THREAD

**Issue by yogi11** [rednaxelaesor/lernOS-Prozessmodellierung#80]
Kleine Verbesserung im Umgang mit den Generaten:

- Im Batchfile die Generate in ein Unterverzeichnis erzeugen
- Das Unterzeichnis in .gitignore aufnehmen

Verbessert und vereinfacht den Workflow

**Comment by rednaxelaesor** [comment]
@yogi11  Das war mein Fehler

**Comment by rednaxelaesor** [comment]
@yogi11 Schau mal die Version 0.2

**Comment by rednaxelaesor** [comment]
Ich habe jetzt alle Endungen der Generaten im gitignote, damit werden sie nie comitted und sind immer nur Teil des Releases.
