### ISSUE TITLE
Aktuelles Feedback zum Lernpfad geben - Daniel

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/lernOS-Prozessmodellierung#82]

**Comment by scivolemo** [comment]
Hallo Alex, ich habe nun versucht den ersten Pull Request zu machen. Vor ein paar Tagen habe ich meinen ersten Branch gelöscht, um die aktuellen Änderungen zu sehen. Ich hoffe, dass es funktioniert hat. Viele Grüße Daneil

**Comment by scivolemo** [comment]
Man merkt beim Durchlesen, wie tief du bzw. ihr im Thema seid. Vor allem merkt man dies beim BDM / DMN. Vorbildlich.

**Comment by rednaxelaesor** [comment]
Super, vielen Dank @scivolemo 
Ich schaue mir das heute Abend gleich mal an.
